# Simple metrics registry for Prometheus `/metrics` scraping

PROM_METRICS = {
    "agent_routes_total": {
        "infra": 0,
        "code": 0,
        "research": 0
    },
    "llm_token_chunks_total": 0
}

def increment_route(specialist: str):
    key = specialist.lower().strip()
    if key in PROM_METRICS["agent_routes_total"]:
        PROM_METRICS["agent_routes_total"][key] += 1

def increment_tokens(count: int = 1):
    PROM_METRICS["llm_token_chunks_total"] += count

def get_prometheus_metrics() -> str:
    """Formats metrics in Prometheus text format."""
    lines = [
        "# HELP agent_routes_total Total times a query was routed to a specialist",
        "# TYPE agent_routes_total counter"
    ]
    for key, val in PROM_METRICS["agent_routes_total"].items():
        lines.append(f'agent_routes_total{{specialist="{key}"}} {val}')
        
    lines.extend([
        "# HELP llm_token_chunks_total Total number of streamed text token chunks generated by specialists",
        "# TYPE llm_token_chunks_total counter",
        f"llm_token_chunks_total {PROM_METRICS['llm_token_chunks_total']}"
    ])
    
    return "\n".join(lines) + "\n"
