import logging
from typing import Dict, Any

try:
    from prometheus_client import Counter, Histogram, generate_latest
except ImportError:
    Counter = None  # type: ignore
    Histogram = None  # type: ignore
    generate_latest = None  # type: ignore

logger = logging.getLogger("metrics")

# Prometheus Counter Metric Definitions
ROUTE_COUNTER = (
    Counter(
        "agent_routes_total",
        "Total times a query was routed to a specialist",
        ["specialist"],
    )
    if Counter
    else None
)
TOKEN_COUNTER = (
    Counter(
        "llm_token_chunks_total",
        "Total number of streamed text token chunks generated by specialists",
    )
    if Counter
    else None
)
PIPELINE_RUNS_COUNTER = (
    Counter("pipeline_runs_total", "Total medallion pipeline runs executed", ["status"])
    if Counter
    else None
)

# In-memory fallback if prometheus_client is absent
_FALLBACK_METRICS: Dict[str, Any] = {
    "agent_routes_total": {"infra": 0, "code": 0, "research": 0},
    "llm_token_chunks_total": 0,
    "pipeline_runs_total": {"completed": 0, "failed": 0},
}


def increment_route(specialist: str) -> None:
    key = specialist.lower().strip()
    if ROUTE_COUNTER:
        try:
            ROUTE_COUNTER.labels(specialist=key).inc()
        except Exception:
            pass
    if key in _FALLBACK_METRICS["agent_routes_total"]:
        _FALLBACK_METRICS["agent_routes_total"][key] += 1


def increment_tokens(count: int = 1) -> None:
    if TOKEN_COUNTER:
        try:
            TOKEN_COUNTER.inc(count)
        except Exception:
            pass
    _FALLBACK_METRICS["llm_token_chunks_total"] += count


def record_pipeline_run(status: str = "completed") -> None:
    s = status.lower().strip()
    if PIPELINE_RUNS_COUNTER:
        try:
            PIPELINE_RUNS_COUNTER.labels(status=s).inc()
        except Exception:
            pass
    if s in _FALLBACK_METRICS["pipeline_runs_total"]:
        _FALLBACK_METRICS["pipeline_runs_total"][s] += 1


def get_prometheus_metrics() -> str:
    """Formats metrics in standard Prometheus text format."""
    if generate_latest:
        try:
            return generate_latest().decode("utf-8")
        except Exception as e:
            logger.warning(f"Prometheus generate_latest failed: {e}")

    lines = [
        "# HELP agent_routes_total Total times a query was routed to a specialist",
        "# TYPE agent_routes_total counter",
    ]
    for key, val in _FALLBACK_METRICS["agent_routes_total"].items():
        lines.append(f'agent_routes_total{{specialist="{key}"}} {val}')

    lines.extend(
        [
            "# HELP llm_token_chunks_total Total number of streamed text token chunks generated by specialists",
            "# TYPE llm_token_chunks_total counter",
            f"llm_token_chunks_total {_FALLBACK_METRICS['llm_token_chunks_total']}",
        ]
    )

    return "\n".join(lines) + "\n"
