# Kong Gateway Configuration (DB-less mode)
env:
  database: "off"
  nginx_proxy_client_body_buffer_size: "10m"
  nginx_proxy_client_max_body_size: "20m"

# Disable unnecessary default features to save CPU/Memory resource constraints
ingressController:
  enabled: true
  installCRDs: false # Helm installs CRDs automatically or we manage them

# Set LoadBalancer for the proxy (exposes public IP on AWS)
proxy:
  type: LoadBalancer
  http:
    enabled: true
  tls:
    enabled: false # We will handle TLS/SSL terminates or let Kong do it locally. For PoC, HTTP is fine.
