# Vault Helm Chart Configuration (Dev Mode with Web UI)
server:
  dev:
    enabled: true
    devRootToken: "root-vault-token"

  ui:
    enabled: true
    serviceType: "ClusterIP"

injector:
  enabled: true
  authPath: "auth/kubernetes"
